// This file should be generated by:
// flutterfire configure
// DO NOT EDIT THIS FILE MANUALLY

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with actual Firebase project details
    // Run: flutterfire configure
    // This will auto-generate the correct configuration for your platform

    // Placeholder - will be replaced by flutterfire configure
    return FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      appId: 'YOUR_APP_ID',
      messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
      projectId: 'shinjuu-league',
      authDomain: 'shinjuu-league.firebaseapp.com',
      databaseURL: 'https://shinjuu-league.firebaseio.com',
      storageBucket: 'shinjuu-league.appspot.com',
      iosBundleId: 'com.petit.works.shinJuuLeague',
      androidClientId: 'YOUR_ANDROID_CLIENT_ID',
    );
  }
}
